Add device virtual removal on error before exit
canonical/edgex-checkbox-provider pull request #46
Opened 2022-10-21 13:55 UTC by farshidtz

Also, add manual connection in case a local build of the platform snap is given.

2022-10-25 16:16 UTC, MonicaisHer requested changes
line 150 and 198 also need to be updated to `snap_remove_all()`

2022-10-25 16:16 UTC, MonicaisHer commented on data/latest/test-rules-engine.sh
> +
```suggestion

snap_remove_all()
{
    snap_remove
    snap remove edgex-device-virtual
}
snap_remove_all
```

2022-10-27 14:06 UTC, farshidtz commented
> line 150 and 198 also need to be updated to `snap_remove_all()`

Those have been removed from main by #47. Changing here will cause conflicts.

2022-10-27 14:34 UTC, MonicaisHer approved these changes
@farshidtz Thank you, looks good.

2022-10-27 15:03 UTC, merged